[versions]
groovy = "3.0.5"
checkstyle = "8.37"

[libraries]
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
groovy-nio = { module = "org.codehaus.groovy:groovy-nio", version.ref = "groovy" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.8.1" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.8.1" }
gradle-test-logger-plugin = "com.adarshr:gradle-test-logger-plugin:3.2.0"

[bundles]
groovy = ["groovy-core", "groovy-json", "groovy-nio"]

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.7.1" }
